---

- name: Download erlang-solutions
  get_url:
    url: https://packages.erlang-solutions.com/erlang-solutions-2.0-1.noarch.rpm
    dest: /tmp/erlang-solutions_2.0_all.rpm
    mode: '0440'

- name: Install erlang-solutions Repository
  shell: rpm -Uvh erlang-solutions-2.0-1.noarch.rpm

- name: Cleanup
  file:
    path: /tmp/erlang-solutions_2.0_all.rpm
    state: absent
