---
dependencies: []

galaxy_info:
  role_name: palava-signaltower
  author: juwi
  description: Palava Signaltower role
  company: "Palava e.V."
  license: "license (BSD, MIT)"
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - web
    - webrtc